INSERT INTO USERDETAILS (USERNAME,PASSWORD,ROLE) VALUES('admin','admin','ADMIN');
INSERT INTO USERDETAILS (USERNAME,PASSWORD,ROLE) VALUES('user1','user1','USER');
INSERT INTO USERDETAILS (USERNAME,PASSWORD,ROLE) VALUES('user2','user2','USER');
INSERT INTO USERDETAILS (USERNAME,PASSWORD,ROLE) VALUES('user3','user3','USER');

